org: planiteasy
app: planiteasy
service: plan-it-easy-frontend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
plugins:
  - serverless-finch

custom:
  client:
    bucketName: plan-it-easy-frontend-2411  # Choose a unique name
    distributionFolder: dist
    indexDocument: index.html
    errorDocument: index.html
    region: ap-south-1